apiVersion: v1
kind: Service
metadata:
    name: "aksdevapp-50af"
    labels:
        app: "aksdevapp-50af"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdevapp-50af"